entrypoint: ./cmd/server/main.go
entrypointArgs: ["--somearg", "somevalue"]

excludePaths: ["vendor", "client"]

hardReload:
  - "*.go"
  - "go.mod"

softReload:
  - "*.html"
  - "*.css"
  - "*.js"
  - "*.tmpl"

generated:
  "*.templ":
    - "task generate/templ"
    - "__soft_reload"

envFiles:
  - ".env"
  - ".env.local"
reloadOnUnhandled: true
proxy:
  enabled: true
  port: 4000
  downstream:
    host: localhost:8081
    timeout: 5
ui:
  enabled: true